services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  product:
    image: maven:latest
    ports:
      - 8080:8080
    volumes:
      - ./product_service:/product
    working_dir: /product
    command:  /bin/sh -c "mvn clean install && mvn spring-boot:run"
    depends_on:
      - db
  customer:
    image: maven:latest
    ports:
      - 8081:8081
    volumes:
      - ./customer_service:/customer
    working_dir: /customer
    command:  /bin/sh -c "mvn clean install && mvn spring-boot:run"
    depends_on:
      - db
  currency:
    build: ./currency_service
    volumes:
      - ./currency_service/cache:/app/cache
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"